### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by tomdyson** [nypublicradio/wagtail-websockets#1]
`pip install git+https://github.com/nypublicradio/wagtail-websockets.git`

fails with

`poetry.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package wagtail-channels`

I imagine this is from https://github.com/nypublicradio/wagtail-websockets/blob/master/pyproject.toml#L2

**Comment by mike-hearn** [comment]
Looks like the latest version of pip v19 added support for pyproject.toml and I missed it because I'm still on v10. Will be fixed momentarily.
